
name: Releases

on: 
  push:
    tags:
    - '*'
jobs:
  releases:
    name: release apk
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11"
      FLUTTER_VERSION: "3.7.3"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk --release
      - uses: ncipollo/release-action@v1
        with:
         artifacts: "build/app/outputs/flutter-apk/*.apk"
